### ISSUE TITLE
suma, resta y multiplicación de hexales y binarios

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-NBbrook#1]
[practicas 1 suma resta de binarios.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-NBbrook/files/12599718/practicas.1.suma.resta.de.binarios.pdf)

**Comment by JoseRodriguez-23620213** [comment]
Portada: 20pts
Procedimiento: 15pts
Figuras: 15pts
Resultados: 15pts

Calificacion: 65pts = 13%

**Comment by josealfredo79** [comment]
Revisado...
